version: '3.8'

name: 'parcel-reception-app'
services:
  postgres:
    image: postgres:16-alpine
    container_name: parcel-reception-app-db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data
